notify : 
  - name : 'stdout'
  - name : 'skype'
    url : 'http://localhost:8787/'

watch : 
  - addr : 'http://github.com/shokai'
    type : 'http'
  - addr : 'github.com'
    type : 'ping'
  - addr : 'http://example.com/auth'
    type : 'http'  
    basic_user : 'username'
    basic_pass : 'password'
  - addr : 'http://example.com.ping.fail/' # HTTP fail sample
    type : 'http'
  - addr : 'example.com.ping.fail' # ping fail sample
    type : 'ping'
